# Base-image-specific config files provide some important information
# about the device type and the limits of its resources.

[general]
image_name = "raspberry-pi-3-base"

[resources]
memory = "600m"
memory-swap = -1
cpus = 1

