# This docker-compose file sets up a virtual bridge network on your local machine.
#
# Helpful if you don't have access to the physical devices/test network, or for
# quickly testing changes that you don't expect to have any bearing on the physical
# network.

version: '3.9'

services:

  remote-cuda-localtest:
    build:
      context: ../
      dockerfile: Dockerfile.cuda
    image: colab-vision-remote-cuda
    container_name: remote-cuda-localtest
#   ports:
#     - "8080:80"  # Publish the container's port 80 to the host's port 8080
    networks:
      - local-bridge-network  # Attach the container to the virtual network
    environment:  # Set environment variables within the container
      - VARIABLE1=value1
      - VARIABLE2=value2
#   volumes:
#     - type: bind  # Bind mount a volume
#       source: ./local/folder/for/container-1
#       target: /path/in/container

  client-no-cuda-localtest:
    build:
      context: ../
      dockerfile: Dockerfile.no-cuda
    image: colab-vision-client-no-cuda
    container_name: client-no-cuda-localtest
#   ports:
#     - "8081:80"
    networks:
      - local-bridge-network
    environment:
      - VARIABLE1=value1
      - VARIABLE2=value2
#   volumes:
#     - type: bind
#       source: ./local/folder/for/container-2
#       target: /path/in/container
    depends_on:  # Don't start building this container until the following is built
      - remote-cuda-localtest

networks:

  my-virtual-network:
    driver: bridge  # Use the default bridge network driver

