#!/bin/bash

# check command line arguments
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <python_version> [--remote <host>]"
    echo "$@"
    echo "$(tput setaf 1)ERROR: No Python version specified.$(tput sgr0)"
    exit 1
fi

python_version=$1

# parse remaining command line arguments
shift
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --remote) remote="$2"; shift;;
        *) echo "Unknown parameter passed: $1"; exit 1;;
    esac
    shift
done

# the install_python script as a single quoted string
install_python_script='
function install_python() {
    if ! pyenv versions --bare | grep -q "^'"$python_version"'$"; then
        echo "  Python version '"$python_version"' not yet installed. Installing..."
        if pyenv install '"$python_version"'; then
            echo "  Python version '"$python_version"' installed successfully."
        else
            echo "  Failed to install Python version '"$python_version"'."
            exit 1
        fi
    else
        echo "  Python version '"$python_version"' is already installed."
    fi
}

install_python
'

if [ -z "$remote" ]; then
    # install locally
    echo "Installing Python version $python_version locally..."
    eval "$install_python_script"
    if pyenv versions --bare | grep -q "^$python_version$"; then
        echo "$(tput setaf 2)Python version $python_version is installed.$(tput sgr0)"
        exit 0
    else
        echo "$(tput setaf 1)Failed to ensure that Python version $python_version is installed.$(tput sgr0)"
        exit 1
    fi
else
    # install remotely
    echo "Installing Python version $python_version on $remote..."
    escaped_script=$(printf '%q' "$install_python_script")
    if ssh -t $remote bash -l -c "$escaped_script"; then
        if ssh -t $remote 'bash -l -c "pyenv versions --bare | grep -q ^'$python_version'$"'; then
            echo "$(tput setaf 2)Python version $python_version is installed on $remote.$(tput sgr0)"
            exit 0
        else
            echo "$(tput setaf 1)Failed to ensure that Python version $python_version is installed on $remote.$(tput sgr0)"
            exit 1
        fi
    else
        echo "$(tput setaf 1)Failed to install Python version $python_version on $remote.$(tput sgr0)"
        exit 1
    fi
fi
