#!/bin/bash
# project_root

# Find the directory of the script
script_dir=$(dirname "$(realpath "$BASH_SOURCE")")

# Move three levels up
project_root=$(realpath "$script_dir/../../../..")

# Output the project root directory
echo "$project_root"
