# information about this config file
meta:
  name: ''
  description: 'The original Alexnet split test designed by Nick Bovee'
  date_created: ''
  last_modified: ''

# dataset configuration
datasets:
  directory: Datasets

# model configuration
models:
  directory: Models

# output configuration
output:
  directory: Output

# node configuration
nodes:
  directory: NodeTypes
  types:

    Client:
      environment:
        python_version: 3.8.17
        pip_version: 23.1.2
      depends_on: Remote
      main_file: run_client.py
      requires_gpu: false
      uses_gpu: false
      supported_cpu_architectures:
      - x86_64
      - arm64
      min_ram_mb: 1000
      supports_multiple_instances: true
      grpc_port: 50051

    Remote:
      depends_on: null
      environment:
        python_version: 3.8.17
        pip_version: 23.1.2
      main_file: run_server.py
      requires_gpu: false
      uses_gpu: true
      supported_cpu_architectures:
      - x86_64
      - arm64
      min_ram_mb: 1000
      supports_multiple_instances: false
      grpc_port: 50051

# overall experiment configuration
runtime:
  presets:
    default:
      Client:
        run_on: any
        num_instances: 1
        output:
          log_directory: Output
          monitor_realtime: true
        input:
          dataset_path: Datasets/test
          type: file_directory
          loader: RemoteFileLoader
          port: 8000
        metrics:
          latency: true
          throughput: true
          power_consumption: true
      Remote:
        run_on: controller
        num_instances: 1
        output:
          log_directory: null
          monitor_realtime: true
        input:
          dataset_path: null
          type: null
          loader: null
          port: null
        metrics:
          latency: true
          throughput: true
          power_consumption: true
      General:


  run_command_parameters:
  - NUM_CLIENTS
  - SPLIT_LAYER
